# Generated by Django 2.1.1 on 2018-11-19 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import website.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('description', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('website', models.URLField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('image', models.ImageField(blank=True, upload_to=website.utils.profile_directory_path)),
            ],
        ),
    ]
